version: "3"

vars:
  APP_MODULE: kt_optimizer.main

tasks:
  default:
    desc: show available tasks
    cmds:
      - task --list

  gui:
    desc: start the Kt optimizer GUI
    cmds:
      - uv run python -m {{.APP_MODULE}}

  sync:
    desc: install/sync dependencies with uv
    cmds:
      - uv sync

  test:
    desc: run tests
    cmds:
      - uv run pytest tests/ -v

  build:
    desc: build Windows exe with PyInstaller
    cmds:
      - uv sync --group build
      - uv run python -m PyInstaller kt_optimizer.spec --distpath dist --workpath build
      - echo "Exe: dist/kt-optimizer.exe"

  lint:
    desc: lint code with ruff
    cmds:
      - uv run ruff check .

  format:
    desc: format code with ruff formatter
    cmds:
      - uv run ruff format .
